### PR TITLE
removed IC2C and Thermal references and files

### PR DESCRIPTION
**Pull request by CassieRoseZA**

### CODE REVIEW

**Comment by skniro** [comment]
I use fabric datagen to generate all version's json files. And ic2 or ic2c use same id. IC2 has fabric version.

**Comment by CassieRoseZA** [comment]
no i can't find any fabric version for ic2

**Comment by skniro** [comment]
I think use tag to hide it in rei/emi jei is a good choice. [REI wiki ](https://chicken-fetch-ve7.craft.me/qj8mHyTVd7qkOZ/b/B4946A69-F58D-4E33-8F71-F97BDBB8EEE7/Entries-in-Entry-List-(Client))

**Comment by skniro** [comment]
> no i can't find any fabric version for ic2

Because ic2's developer only publish test version in github.

**Comment by skniro** [comment]
[github link](https://github.com/IndustrialCraftMC/IndustrialCraft2/releases/tag/ic2_2_9_40_1192)

**Comment by CassieRoseZA** [comment]
thats for 1.19.2 
image
this PR is only for 1.20.1

**Comment by skniro** [comment]
I want all version code are same.It could make i easy update all version.And i also use 1.20's fabric datagen to generate all json files(include forge,neoforge and old fabric version)

**Comment by CassieRoseZA** [comment]
but why your causing problems with different codebases your trying to manage 5 versions all with the same code something is bound to break and you really should think of maybe doing a multiloader setup as its much better aswell as you need to think WHY DO YOU PUT FORGE MODS ON A FABRIC MOD?

**Pull request closed without merging**
